env = Environment()

# env['CPPPATH'] = [
#     '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/include/python2.7',
#     '/usr/local/include',
#     '/usr/local/opt/sqlite/include',
#     '/usr/local/include',
# ]

#env['LIBPATH']  = [
#    '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config'#,
#]

env['LIBS'] = [
    #'python2.7',
    #'boost_python',
]

env['LINKFLAGS'] = [
    '-L/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config',
    '-ldl',
    '-framework',
    'CoreFoundation',
    '-lpython2.7',
    '-lboost_python',
]

env['CPPFLAGS'] = [
    '-I/usr/local/include',
    '-I/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/include/python2.7',
    '-fno-strict-aliasing',
    '-fno-common',
    '-dynamic',
    '-I/usr/local/opt/sqlite/include',
    '-DNDEBUG',
    '-g',
    '-fwrapv',
    '-O3',
    '-Wall',
    '-Wstrict-prototypes',
]

env['SHLIBPREFIX'] = ''
env['SHLIBSUFFIX'] = '.so'

# env['CPPPATH'] = ['-I/usr/local/Cellar/python3/3.3.5/Frameworks/Python.framework/Versions/3.3/include/python3.3m -I/usr/local/Cellar/python3/3.3.5/Frameworks/Python.framework/Versions/3.3/include/python3.3m -Wno-unused-result -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/sqlite/include']

env.SharedLibrary('coordinates', ['converter.cpp'])